name: Go

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: huaji-bot
  IMAGE_NAME_FULL: ghcr.io/nbtca/huaji-bot
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write


    steps:
    - name: Login DockerHub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}   

    - name: Build and Push to DockerHub
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        no-cache: true
        # target: deploy
        push: true
        platforms: linux/amd64
        tags: |
          ${{ env.IMAGE_NAME_FULL }}:latest

    - name: ssh pipelines
      uses: cross-the-world/ssh-pipeline@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        user: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.ACCESS_TOKEN }}
        connect_timeout: 10s
        script: |
          cd /home/nbtca/weekend/bot
          docker-compose stop && docker-compose rm -f
          docker rmi ${{ env.IMAGE_NAME_FULL }}
          docker-compose up -d